### ISSUE TITLE
Pandas Notebook review

### ISSUE THREAD

**Issue by a1singh** [words-sdsc/edX#11]
@zonca : when you get time, please review the Pandas Notebook, thanks !

**Comment by zonca** [comment]
@a1singh some suggestions:

* better specify exactly which dataset the students have to download, there are many on that webiste
* if you unzip `ml-20m.zip` it creates the folder `ml-20m`, so I would use that as default folder, not `movielens`
* `ratings.describe()['rating']` better do `ratings['rating'].describe()` otherwise you compute statistics for all columns
* cell 8 9 10, it is confusing to print `shape` in the same output cell, what about using  a different cell?
* histogram: I don't think you need the slicing with `[:]`
* the section on merging is great!
* in **Split genres** in multiple columns, you might process the data to have a column `isComedy`, `isFantasy` which are boolean
* Get an error: `KeyError: "['year'] not in index"` in line:

        yearly_average = joined[['year','rating']].groupby('year', as_index=False).mean()

**Comment by a1singh** [comment]
@zonca:

Thanks for detailed feedback. I have incorporated your suggestions and pushed the latest version back to Git.
