### ISSUE TITLE
Numpy notebook with WIFIRE data 

### ISSUE THREAD

**Issue by a1singh** [words-sdsc/edX#6]
- This Notebook will use WIFIRE datasets & numpy

**Comment by zonca** [comment]
@a1singh I reviewed this notebook, looks good, just a few notes:

* you need more markdown explanation for people to understand what is going on
* do not use `filter` as a variable name, it is function in the Python standard library, in fact it shows up green in the notebook, it is confusing
* it is more standard in Python to use `_` instead of camel case, so change `totalRows` to `total_rows`
* at the top of the notebook, list the required packages, like `scipy` or `skimage`

**Comment by a1singh** [comment]
@zonca : thanks for the review. I've made the changes and added some more content. Please let me know how it looks now.

**Comment by zonca** [comment]
@a1singh good, another couple of suggestions,

* better use Markdown cells instead of python comments, they are more readable, you can also use some formatting to make things clearer, like bullet points, bold, also you can do titles to divide subsections of your notebook. ALso a description at the beginning would help understand the logic 
* in cell 6 `# BLUE Pixel intensity denotes `? something is missing
* you might add an histogram maybe to show the color content of the image?
* Cell 7, better explain that the first 2 are sizes, the 3rd RGB colors
*

**Comment by a1singh** [comment]
@zonca : thanks for detailed feedback. I've improved the notebook with your suggestions.


-----
review 1 : COMPLETED & FIXED
-----
